/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt 
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java 
 */
package br.com.ifba.springprg03.curso.view;

import br.com.ifba.springprg03.curso.controller.CursoIController;
import br.com.ifba.springprg03.curso.entity.Curso;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author fabricio
 */
@org.springframework.stereotype.Component
public class CursoEditar extends javax.swing.JFrame {

    private Long idCurso;
    
    @Autowired
    private CursoIController cursoController;
    
    /**
     * O ÚNICO CONSTRUTOR DA CLASSE: Padrão, vazio e sem parâmetros.
     * Isso impede o Spring de travar na inicialização!
     */
    public CursoEditar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    /**
     * Método que recebe o curso e joga os dados na tela
     */
    public void carregarDados(Curso cursoParaEditar) {
        if (cursoParaEditar != null) {
            this.idCurso = cursoParaEditar.getId(); 

            txtnomeCurso.setText(cursoParaEditar.getNome());
            txtcodigoCurso.setText(cursoParaEditar.getCodigo());
            cbModalidade.setSelectedItem(cursoParaEditar.getModalidade());
            txtVagas.setText(String.valueOf(cursoParaEditar.getVagas() != null ? cursoParaEditar.getVagas() : 0));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltextoCurso = new javax.swing.JLabel();
        lblTextoInicial = new javax.swing.JLabel();
        lbltrxtoCodigo = new javax.swing.JLabel();
        lblModalidade = new javax.swing.JLabel();
        lblImagemCurso = new javax.swing.JLabel();
        lblquantidadesVagas = new javax.swing.JLabel();
        pnlcorpoCadastraCurso = new javax.swing.JPanel();
        txtnomeCurso = new javax.swing.JTextField();
        txtcodigoCurso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbltextoCurso1 = new javax.swing.JLabel();
        lblTextoInicial1 = new javax.swing.JLabel();
        lbltrxtoCodigo1 = new javax.swing.JLabel();
        lblModalidade1 = new javax.swing.JLabel();
        lblImagemCurso1 = new javax.swing.JLabel();
        cbModalidade = new javax.swing.JComboBox<>();
        btnsalvaNovoCurso = new javax.swing.JButton();
        txtVagas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lbltextoCurso.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbltextoCurso.setText("INFORME O NOME DO NOVO CURSO");

        lblTextoInicial.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        lblTextoInicial.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoInicial.setText("ALTERA DADOS DO CURSO");

        lbltrxtoCodigo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbltrxtoCodigo.setText("INFORME O CODIGO DO NOVO CURSO");

        lblModalidade.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblModalidade.setText("INFORME A MODALIDADE DO CURSO");

        lblImagemCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/educacao(1).png"))); // NOI18N

        lblquantidadesVagas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblquantidadesVagas.setText("INFORME A QUANTIDADE DE VAGAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTextoInicial)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbltextoCurso)
                                .addComponent(lbltrxtoCodigo)
                                .addComponent(lblModalidade)
                                .addComponent(lblquantidadesVagas)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagemCurso)
                        .addGap(150, 150, 150))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTextoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbltextoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltrxtoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblModalidade)
                .addGap(42, 42, 42)
                .addComponent(lblquantidadesVagas)
                .addGap(27, 27, 27)
                .addComponent(lblImagemCurso)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 590));

        pnlcorpoCadastraCurso.setBackground(new java.awt.Color(0, 153, 153));
        pnlcorpoCadastraCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeCursoActionPerformed(evt);
            }
        });
        pnlcorpoCadastraCurso.add(txtnomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 430, 44));

        txtcodigoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoCursoActionPerformed(evt);
            }
        });
        pnlcorpoCadastraCurso.add(txtcodigoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 430, 43));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        lbltextoCurso1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbltextoCurso1.setText("INFORME O NOME DO NOVO CURSO");

        lblTextoInicial1.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        lblTextoInicial1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoInicial1.setText("CADASTRA UM NOVO CURSO");

        lbltrxtoCodigo1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbltrxtoCodigo1.setText("INFORME O CODIGO DO NOVO CURSO");

        lblModalidade1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblModalidade1.setText("INFORMR A MODALIDADE DO CURSO");

        lblImagemCurso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/educacao(1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTextoInicial1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbltrxtoCodigo1)
                                .addComponent(lbltextoCurso1)
                                .addComponent(lblModalidade1)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblImagemCurso1)
                        .addGap(137, 137, 137))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblTextoInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lbltextoCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lbltrxtoCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblModalidade1)
                .addGap(42, 42, 42)
                .addComponent(lblImagemCurso1)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pnlcorpoCadastraCurso.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 700));

        cbModalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRESECIAL", "SEMI - PRESECIAL", "EAD", " ", " " }));
        cbModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModalidadeActionPerformed(evt);
            }
        });
        pnlcorpoCadastraCurso.add(cbModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 180, 50));

        btnsalvaNovoCurso.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        btnsalvaNovoCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao-adicionar.png"))); // NOI18N
        btnsalvaNovoCurso.setText("SALVA ALTERAÇÕES");
        btnsalvaNovoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvaNovoCursoActionPerformed(evt);
            }
        });
        pnlcorpoCadastraCurso.add(btnsalvaNovoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 330, 70));
        pnlcorpoCadastraCurso.add(txtVagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 430, 50));

        getContentPane().add(pnlcorpoCadastraCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeCursoActionPerformed

    private void txtcodigoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoCursoActionPerformed

    private void cbModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModalidadeActionPerformed

    private void btnsalvaNovoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvaNovoCursoActionPerformed


        try{
            Curso cursoAtualizado = new Curso();
            cursoAtualizado.setId(this.idCurso); 
            cursoAtualizado.setNome(txtnomeCurso.getText());
            cursoAtualizado.setCodigo(txtcodigoCurso.getText());
            cursoAtualizado.setModalidade(cbModalidade.getSelectedItem().toString());

            try {
                cursoAtualizado.setVagas(Integer.valueOf(txtVagas.getText()));
            } catch(NumberFormatException e) {
                cursoAtualizado.setVagas(0); 
            }

            // CHAMADA CORRETA: O Controller e o Service cuidam do Hibernate para você
            cursoController.update(cursoAtualizado);

            JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso!");
            this.dispose(); 

        }catch(RuntimeException e){
            // Captura erros de validação do Service
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnsalvaNovoCursoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvaNovoCurso;
    private javax.swing.JComboBox<String> cbModalidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagemCurso;
    private javax.swing.JLabel lblImagemCurso1;
    private javax.swing.JLabel lblModalidade;
    private javax.swing.JLabel lblModalidade1;
    private javax.swing.JLabel lblTextoInicial;
    private javax.swing.JLabel lblTextoInicial1;
    private javax.swing.JLabel lblquantidadesVagas;
    private javax.swing.JLabel lbltextoCurso;
    private javax.swing.JLabel lbltextoCurso1;
    private javax.swing.JLabel lbltrxtoCodigo;
    private javax.swing.JLabel lbltrxtoCodigo1;
    private javax.swing.JPanel pnlcorpoCadastraCurso;
    private javax.swing.JTextField txtVagas;
    private javax.swing.JTextField txtcodigoCurso;
    private javax.swing.JTextField txtnomeCurso;
    // End of variables declaration//GEN-END:variables

}
