/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author fabricio
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    
    //construtor define a frase inicial usando tags HTML
    public TelaGenio() {
        initComponents();
        lblFrase.setText("<html>Vou pensar em um número de 1 a 5. Tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlContenerTela = new javax.swing.JPanel();
        lblImagemAkinatorpng = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        lblImagemBalaopng = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pnlContenerTela.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenerTela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagemAkinatorpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/fb2cbe0595615d8e873a485df8cad81e (1) (1) (1).jpg"))); // NOI18N
        pnlContenerTela.add(lblImagemAkinatorpng, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 253));

        lblValor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(0, 0, 204));
        lblValor.setText("Valor");
        pnlContenerTela.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 70, 50));

        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        pnlContenerTela.add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 90, 40));

        lblImagemBalaopng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/chat (1).png"))); // NOI18N
        pnlContenerTela.add(lblImagemBalaopng, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lblFrase.setText("Frase");
        pnlContenerTela.add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 180, 84));

        btnPalpite.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnPalpite.setForeground(new java.awt.Color(0, 51, 204));
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        pnlContenerTela.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenerTela, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenerTela, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        // gerar um número aleatório entre 1 e 5
        double n = 1 + Math.random() * (6 - 1);
        int valor = (int) n;
        
        //obtem o palpite do usuário
        int num = Integer.parseInt(spnValor.getValue().toString());
        
        // definição das frases de resposta
        String frase1 = " ACERTOU!";
        String frase2 = "<html>  VOCÊ ERROU! Penssei no numero: <html> " + valor;
        
        // operador ternário para decidir o resultado
        String res = (valor == num)?frase1:frase2;
        
        //imprimi a resposta
        lblFrase.setText(res);
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblImagemAkinatorpng;
    private javax.swing.JLabel lblImagemBalaopng;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlContenerTela;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
