/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade07.view;

/**
 *
 * @author fabricio
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTesto = new javax.swing.JLabel();
        pnlFormaPagamento = new javax.swing.JPanel();
        spnPagamento = new javax.swing.JSpinner();
        btnCalcularValor = new javax.swing.JButton();
        pnlRealizarPagamento = new javax.swing.JPanel();
        txtTextoPagamento = new javax.swing.JLabel();
        lblValorPagamento = new javax.swing.JLabel();
        btnRealizaPagamento = new javax.swing.JButton();
        pnlValor = new javax.swing.JPanel();
        lblTextoCompra = new javax.swing.JLabel();
        lblImagenPedidos = new javax.swing.JLabel();
        txtValorOriginal = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTesto.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTesto.setText("Informe a forma de pagamento");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblTesto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTesto)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlFormaPagamento.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormaPagamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        spnPagamento.setModel(new javax.swing.SpinnerListModel(new String[] {"1 --> Cartão", "2 --> Dinheiro", "3 --> Pix"}));

        btnCalcularValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade07/images/calculadora(2).png"))); // NOI18N
        btnCalcularValor.setText("Calcular Valor");
        btnCalcularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormaPagamentoLayout = new javax.swing.GroupLayout(pnlFormaPagamento);
        pnlFormaPagamento.setLayout(pnlFormaPagamentoLayout);
        pnlFormaPagamentoLayout.setHorizontalGroup(
            pnlFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagamentoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(spnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnCalcularValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormaPagamentoLayout.setVerticalGroup(
            pnlFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagamentoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularValor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlRealizarPagamento.setBackground(new java.awt.Color(255, 255, 255));
        pnlRealizarPagamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTextoPagamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtTextoPagamento.setText("O valor final do pagamento e: ");

        lblValorPagamento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblValorPagamento.setText("0.0");

        btnRealizaPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade07/images/forma-de-pagamento.png"))); // NOI18N
        btnRealizaPagamento.setText("Realizar Pagamento");
        btnRealizaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizaPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRealizarPagamentoLayout = new javax.swing.GroupLayout(pnlRealizarPagamento);
        pnlRealizarPagamento.setLayout(pnlRealizarPagamentoLayout);
        pnlRealizarPagamentoLayout.setHorizontalGroup(
            pnlRealizarPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRealizarPagamentoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtTextoPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRealizaPagamento)
                .addGap(17, 17, 17))
        );
        pnlRealizarPagamentoLayout.setVerticalGroup(
            pnlRealizarPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRealizarPagamentoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlRealizarPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTextoPagamento)
                    .addComponent(lblValorPagamento)
                    .addComponent(btnRealizaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlValor.setBackground(new java.awt.Color(255, 255, 255));
        pnlValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTextoCompra.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoCompra.setText("Informe o valor da compra");

        lblImagenPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade07/images/pedido.png"))); // NOI18N

        txtValorOriginal.setText("0.0");

        javax.swing.GroupLayout pnlValorLayout = new javax.swing.GroupLayout(pnlValor);
        pnlValor.setLayout(pnlValorLayout);
        pnlValorLayout.setHorizontalGroup(
            pnlValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTextoCompra)
                .addGap(27, 27, 27)
                .addComponent(txtValorOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblImagenPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlValorLayout.setVerticalGroup(
            pnlValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pnlValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoCompra)
                    .addComponent(lblImagenPedidos)
                    .addComponent(txtValorOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRealizarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRealizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizaPagamentoActionPerformed
        // TODO add your handling code here:
        String mensagem = "Pagamento de R$ " + lblValorPagamento.getText() + " realizado!";
        javax.swing.JOptionPane.showMessageDialog(this, mensagem, "Recibo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRealizaPagamentoActionPerformed

    private void btnCalcularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularValorActionPerformed
        try {
        String textoValor = txtValorOriginal.getText().replace(",", ".");
        double valorCompra = Double.parseDouble(textoValor);
        
        // verifica a opção no Spinner
        String opcao = spnPagamento.getValue().toString();
        Pagamento pagamento;
            
        // condição para a escolhar do tipo de pagamento
        if(opcao.contains("Dinheiro")){
            pagamento = new PagamentoDinheiro();
        }else if (opcao.contains("Cartão")){
            pagamento = new PagamentoCartao();
        }else{
            pagamento = new PagamentoPix();
        }

        // calcula o total
        double valorFinal = pagamento.calcularTotal(valorCompra);
        
        // eibe o resultado do valculo de pagamento
        lblValorPagamento.setText(String.format("%.2f", valorFinal));
        
        } catch (NumberFormatException e) {
            // se o usuário digitar letras ou deixar vazio, exibe uma mensagem de erro
            javax.swing.JOptionPane.showMessageDialog(this, 
                "insira um valor valido para válido para a compra.", 
                "Erro de Entrada", 
                javax.swing.JOptionPane.ERROR_MESSAGE);

            txtValorOriginal.requestFocus(); // Coloca o cursor de volta no campo de erro
        }
    }//GEN-LAST:event_btnCalcularValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularValor;
    private javax.swing.JButton btnRealizaPagamento;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblImagenPedidos;
    private javax.swing.JLabel lblTesto;
    private javax.swing.JLabel lblTextoCompra;
    private javax.swing.JLabel lblValorPagamento;
    private javax.swing.JPanel pnlFormaPagamento;
    private javax.swing.JPanel pnlRealizarPagamento;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlValor;
    private javax.swing.JSpinner spnPagamento;
    private javax.swing.JLabel txtTextoPagamento;
    private javax.swing.JTextField txtValorOriginal;
    // End of variables declaration//GEN-END:variables
}
